### ISSUE TITLE
Decoding a falsy http response body causes error

### ISSUE THREAD

**Issue by lotuc** [metosin/muuntaja#134]
`muuntaja.core/decode-response-body` will throw error on falsy values:

```
(require '[muuntaja.core :as m])

(m/decode-response-body
 {:body "null" :headers {"Content-Type" "application/json"}})
(m/decode-response-body
 {:body "false" :headers {"Content-Type" "application/json"}})
(m/decode-response-body
 {:body "false" :headers {"Content-Type" "application/edn"}})
```

It's caused by the code [here](https://github.com/metosin/muuntaja/blob/83f7f707b69b3111668856804733c4fd17373159/modules/muuntaja/src/muuntaja/core.clj#L506C16-L506C16).

**Comment by ikitommi** [comment]
Oh, that's not good. PR welcome.
