### ISSUE TITLE
Issues composing Muuntaja with ring-jetty9-adapter 0.30.x / Jetty 12.x

### ISSUE THREAD

**Issue by jasonjckn** [metosin/muuntaja#138]
This issue was discovered in the context of trying to get jetty 12.x working with muuntaja/reitit.

**PROPOSED CHANGE**

Make this a default setting for the application/json decoder 
_(failing that, add an kwargs option for this)._ 

```
 (doto (muuntaja.format.json/object-mapper! options)
          (.enable com.fasterxml.jackson.databind.DeserializationFeature/FAIL_ON_TRAILING_TOKENS))
```
JavaDoc: " Feature could alternatively be called READ_FULL_STREAM, since it effectively verifies that input stream contains only as much data as is needed for binding the full value, and nothing more (except for possible ignorable white space or comments, if supported by data format). " [here](https://fasterxml.github.io/jackson-databind/javadoc/2.9/com/fasterxml/jackson/databind/DeserializationFeature.html#FAIL_ON_TRAILING_TOKENS)

Here's what the working code looks like ( muuntaja + ring-jetty9-adapter 0.30 + jetty12) when its moved outside of Muuntaja / configuration 
<img width="804" alt="image" src="https://github.com/metosin/muuntaja/assets/550839/29adc78f-a951-4c10-8661-0672495cfee3">

**WHY**

In a nutshell, HTTP Requests Input Streams should be fully consumed until read() returns -1 , otherwise there's problems (see  [thread](https://github.com/sunng87/ring-jetty9-adapter/issues/113#issuecomment-1712517411), There's a bunch of discussion with reproduction examples. ). And by default jackson-core is lazy, if you call readValue, it'll readMapAndClose, eagerly close the stream, before read()'ing -1. 

I believe this wasn't an issue before because ring-jetty9-adapter has previously been built ontop of a high level servlet API, but is now ontop of the lower level jetty core API, nonetheless I think this is good practice, and i feel uncomfortable writing weird hacks ontop of the core API to try to consume the stream if it wasn't fully consumed, clojure would be the only project to do that. Other non-clojure [projects](https://github.com/FasterXML/jackson-jaxrs-providers/issues/108) that sit a couple levels above Jetty have taken the FAIL_ON_TRAILING_TOKENS approach. 

I'll send a PR, if someone can give preliminary 'okay'

**Comment by Deraen** [comment]
Btw. you can provide your own ObjectMapper instance to the built-in decoder easier by providing mapper instance in the options map:

`:decoder [muunta.format.json/decoder {:mapper (doto ^ObjectMapper ...)}]`

No need to create your own `decoder` instance and I think it isn't a hack to provide the mapper instance directly, there is bunch of options that aren't available through Jsonista.

Still makes sense to find a solution to handle this automatically.

**Comment by jasonjckn** [comment]
I encountered a pathological case where FAIL_ON_TRAILING_TOKENS wasn't consuming the full stream, this is in spite of the docs say "could alternatively be called READ_FULL_STREAM", 

(with jetty 12.x)

Scenario #1, without FAIL_ON_TRAILING_TOKENS and valid JSON ("close before EOF")
<img width="1851" alt="image" src="https://github.com/metosin/muuntaja/assets/550839/e8403ccc-3d64-4ff0-86b5-806a6efd9ce1">

Scenario #2, with FAIL_ON_TRAILING_TOKENS enabled and valid JSON payload (good output) 
<img width="1731" alt="image" src="https://github.com/metosin/muuntaja/assets/550839/40054433-961a-4d3e-9b84-30e2843197d9">

Scenario #3, with FAIL_ON_TRAILING_TOKENS enabled and invalid JSON payload  ("closed before EOF")
<img width="1867" alt="image" src="https://github.com/metosin/muuntaja/assets/550839/112eaf11-f3c5-4228-9456-53e2646ba6f0">

So I went back to the drawing board.... and it turns out disabling com.fasterxml.jackson.core.JsonParser$Feature/AUTO_CLOSE_SOURCE works in all cases. 

Scenario #4, with AUTO_CLOSE_SOURCE disabled  and invalid JSON / parse error (good)
<img width="1764" alt="image" src="https://github.com/metosin/muuntaja/assets/550839/529e509e-d70f-4c6c-a388-dbc5b0c8d753">

At the very least we need a flag for disabling AUTO_CLOSE_SOURCE, i can send a PR.
I'm not confident at all in making that the default value though.... i think i would want to test multiple versions of jetty and other clojure webservers to see how it behaves. But the -only- option i'm aware of if you want to use jetty 12.x. 

Shall I send a PR (?) for flags AUTO_CLOSE_SOURCE, and FAIL_ON_TRAILING_TOKENS (may as well do this too).

**Comment by jasonjckn** [comment]
We're probably not going to need AUTO_CLOSE_SOURCE flags after all, changes were made further down the stack in Jetty 12.0.2, more details here https://github.com/sunng87/ring-jetty9-adapter/issues/113

I'm going to tentatively close this issue.

**Comment by Deraen** [comment]
Thanks @jasonjckn for the investigation. The ring-jetty9-adapter issue was an interesting read and a view into Jetty details.
