### ISSUE TITLE
Adding :body-params to :params

### ISSUE THREAD

**Issue by kanwei** [metosin/muuntaja#19]
What's the best way to do this? Switched from r-m-f and it seems that muuntaja uses :body-params instead of :form-params, so there should be a way for the :body-params to be merged into :params.

**Comment by kanwei** [comment]
I see that muuntaja.core/wrap-params does exist. Should this be documented in the readme? :)

**Comment by ikitommi** [comment]
Indeed, there could be a link "coming from r-m-f" pointing to https://github.com/metosin/muuntaja/wiki/Differences-to-existing-formatters with a sample configuration to get just the same results.

**Comment by ikitommi** [comment]
added the link.
