### ISSUE TITLE
Handle different charsets

### ISSUE THREAD

**Issue by ikitommi** [metosin/muuntaja#2]
ring-middleware-format negotiated charsets, muuntaja currently does not. There is a branch [charset](https://github.com/metosin/muuntaja/tree/charsets), which try to do this, but still not sure how this should be done. Someone should figure out:

* IN: what is and can be done in the adapter/http-server/container -level? e.g. can it do automatic stream conversion from e.g. `ISO-8859-1` to `UTF-8`?
* OUT: if we return a String to the http-server with a content-type & a charset, will them all produce a correctly encoded byte-stream already?

For now, the charsets are negotiated, but not used.

**Comment by miikka** [comment]
If Muuntaja does the charset negotiation, wouldn't it be simplest to just consume and produce byte streams?

**Comment by ikitommi** [comment]
All-stream sounds like a good idea. 

Still, would it be faster just to write the result into a http-server output streams?  Ring 1.6.0 will have the [StreamableResponseBody](https://github.com/ring-clojure/ring/blob/545ed6ea2299a2f951977c2a8c001eacf6f623d4/ring-core/src/ring/core/protocols.clj) to allow to do this. Maybe:

* IN: byte stream (`decode`)
* OUT: either byte stream (`encode`) or a function taking an OutputStream (`write-to-stream`)

e.g. Transit would be instead of current (original from r-m-f):

```clj
(defn make-transit-encoder
  [type {:keys [verbose] :as options}]
  (fn [data]
    (let [out (ByteArrayOutputStream.)
          full-type (if (and (= type :json) verbose)
                      :json-verbose
                      type)
          wrt (transit/writer out full-type options)]
      (transit/write wrt data)
      (ByteArrayInputStream.
        (.toByteArray out)))))
```

=>

```clj
(defn make-streaming-transit-encoder
  [type {:keys [verbose] :as options}]
  (let [full-type (if (and (= type :json) verbose)
                    :json-verbose
                    type)]
    (fn [data]
      (fn [stream]
        (let [writer (transit/writer stream full-type options)]
          (transit/write writer data)
          (.flush writer))))))
```

Not sure if the Transit Writer accepts encoding thou.

With this, Muuntaja MW could return a custom Response record, satisfying the `ring.core.protocols.StreamableResponseBody` and thus hooking the stream into a http-output stream.

Returning always a byte stream would be simpler, if the perf ~ the same, I would go with the all-streams.

**Comment by ikitommi** [comment]
And the current impl to return String from some formats (like JSON) is a bad idea => testing muuntaja-apps without http-server is awful, as the body could be a string or a stream.

**Comment by ikitommi** [comment]
Had to make a quick study how Ring 1.6.0 works with streams. Generated JSON in three flavours: as String, streamed response directly to output and an InputStream. Read the populated output stream  into a string to ensure that all work is done. (without reading, results were: 4.5µs, 1.8µs, 1.5µs).

* returning String representations is the e2e slowest, Ring uses `io/writer` to write.
* writing results directly to streams or returning an InputStream doesn't seem to matter much. `io/copy` was used in both.

so, I would change everything to return an byte stream, with correct encoding.

```clj
##################
## json: string ##
##################

{"orders":[{"id":1,"products":[1,3,2]},{"id":2,"products":[4,3,2]}]}
Evaluation count : 87348 in 6 samples of 14558 calls.
             Execution time mean : 6.953316 µs
    Execution time std-deviation : 556.924343 ns
   Execution time lower quantile : 6.527194 µs ( 2.5%)
   Execution time upper quantile : 7.697478 µs (97.5%)
                   Overhead used : 1.657765 ns

###########################
## json: write-to-stream ##
###########################

{"orders":[{"id":1,"products":[1,3,2]},{"id":2,"products":[4,3,2]}]}
Evaluation count : 150192 in 6 samples of 25032 calls.
             Execution time mean : 4.096724 µs
    Execution time std-deviation : 196.657986 ns
   Execution time lower quantile : 3.874303 µs ( 2.5%)
   Execution time upper quantile : 4.363335 µs (97.5%)
                   Overhead used : 1.657765 ns

#######################
## json: inputstream ##
#######################

{"orders":[{"id":1,"products":[1,3,2]},{"id":2,"products":[4,3,2]}]}
Evaluation count : 153426 in 6 samples of 25571 calls.
             Execution time mean : 3.922789 µs
    Execution time std-deviation : 133.078206 ns
   Execution time lower quantile : 3.790671 µs ( 2.5%)
   Execution time upper quantile : 4.085501 µs (97.5%)
                   Overhead used : 1.657765 ns
```

**Comment by miikka** [comment]
Returning streams vs. writing to a provided stream: I think this affects how easy it is to do streaming or async stuff, but I haven't thought out which way is better.

(I don't think the Transit implementation allows you to specify charset. For JSON, input is autodetected UTF-8/16/32 and output is UTF-8. MessagePack is just bytes anyway.)

**Comment by ikitommi** [comment]
Pushed all-streams & the tests against `ring.core.protocols.StreamableResponseBody` into a separate branch. There are now separate write-to-stream implementations for JSON and TRANSIT, used in the perf tests. 

Summary: returning streams seems to be 2-3 faster than returning Strings. Ring does a lot of regexp-parsing to extract the charset when String are returned. With streams, one can set 'em directly. 

tests: https://github.com/metosin/muuntaja/blob/46ab4d794eefb47a7cd07bbd956ce81b83d68861/test/muuntaja/formats_perf_test.clj

Would love to hear if the tests are ill in some way, eg. testing wrong things. Tried to read source of HttpKit, Jetty and Netty for how they use streams. In tests, the ServletOutputStreams are just ByteArrayOuputStreams.

**Comment by ikitommi** [comment]
done.
