### ISSUE TITLE
muuntaja.json decoder-options

### ISSUE THREAD

**Issue by ikitommi** [metosin/muuntaja#23]
Cheshire has `:key-fn`, `:array-coerce-fn` and `:bigdecimals?`,  Ring-json has  `:keywords?` (setting the `:key-fn` actually), Muuntaja has now `:keywordize?`.

Would be good to check the `muuntaja.json` and `muuntaja.format.json/make-muuntaja-json-encoder` options before release.

**Comment by miikka** [comment]
Migrated to https://github.com/metosin/jsonista/issues/5
