### ISSUE TITLE
Clojars binary doesn't supports OpenJDK 1.7

### ISSUE THREAD

**Issue by jaromil** [metosin/muuntaja#50]
Not sure this is intended behavior because of a software dependency from Java 1.8. If not then it may be simply an issue created by the platform you use to build the binary distributed on clojars. The effect is that any project depending from muuntaja loses backward support for openjdk 1.7.
I hope you contemplate this as a bug, it would be nice to grant backward compatibility.

**Comment by miikka** [comment]
Hi! Yes, we consider this as a bug, Muuntaja is supposed to support Java 1.7. This was already fixed for the upcoming release 0.3.0 in #43/#44, but 0.2.1 has been released before that.

While we're going to release 0.3.0 out real soon now, maybe we should push out 0.2.2 just to fix this.

**Comment by miikka** [comment]
Okay, I pushed out `[metosin/muuntaja 0.2.2]` which should be build against Java 1.7.

**Comment by jaromil** [comment]
Great! thanks :^) no rush, but you may want to update compojure-api alpha2 to muuntaja 0.2.2 and trigger a new build, since that is your most popular package bringing in muuntaja (at least that's how I found this).
I love your work btw, its great stuff, please keep it up! just started coding something with it and will certainly do more. I haven't used all features available, however my code in fxc-webapi runs flawlessly with both compojure-api 1.1.10 and 2.0.0-alpha1 so that's also some nice backward compatibility you have there. Ciao

**Comment by miikka** [comment]
The next compojure-api alpha should be coming out soon and it will depend on muuntaja 0.2.2.
