### ISSUE TITLE
Cannot use muuntaja.core without depending on Ring

### ISSUE THREAD

**Issue by Fingerzam** [metosin/muuntaja#58]
The namespace `muuntaja.protocols` requires `ring.core.protocols`, but there is no dependency on `ring/ring-core` in `project.clj`. Trying to compile a project depending on Muuntaja and just requiring `muuntaja.core` results in an error

```
java.io.FileNotFoundException: Could not locate ring/core/protocols__init.class or ring/core/protocols.clj on classpath., compiling:(protocols.clj:1:1)
Exception in thread "main" java.io.FileNotFoundException: Could not locate ring/core/protocols__init.class or ring/core/protocols.clj on classpath., compiling:(protocols.clj:1:1)
```

**Comment by ikitommi** [comment]
Thanks for reporting. Should be fixed in `[metosin/muuntaja "0.4.3-20180111.201932-1"]`.
