### ISSUE TITLE
Pick default charset when there are multiple equally-preferred options in the Accept header

### ISSUE THREAD

**Issue by miikka** [metosin/muuntaja#79]
Some HTTP clients send a huge list of charsets they can accept without specifying their preferred option with `q=`. E.g. apparently Spring sends all the charsets JVM supports in alphabetical order.  Now we pick the first one, but we could do a favor to the users and pick `:default-charset` if it's in the list – or maybe this should be a separate option. I think people would prefer getting UTF-8 instead of, say, Big5.

**Comment by ikitommi** [comment]
This is a good idea.

**Comment by MrOerni** [comment]
There may even be a bug when encoding to a charset.
In my case the last entry in `Accept-Charset` is: `x-windows-iso2022jp` (`UTF-8, UTF-16, ...` are also in this list)

So apparently everything is coded with this charset, *iff* I return a map. (When I return a string, then no charset is set at all)

Now I have an `ö` in my response which isn't in this charset. So the character gets encoded as: `1b 24 42 21 29 1b 28 42` which (according to this http://www.fileformat.info/info/charset/x-windows-iso2022jp/list.htm) is a `FULLWIDTH QUESTION MARK (U+FF1F)`

This could be done in UTF-8 with a single `U+00F6`

**Comment by miikka** [comment]
@MrOerni, could you clarify that which part of this behavior you consider a bug / what would you expect? Clearly it's not ideal, I just want to check that we're on the same page.

**Comment by MrOerni** [comment]
True. That's why I like this proposal. 

I noticed that if I set the charset on my own, it will be set as a header in the response, but the encoding is still in this wrong charset. 
Maybe this could be used.

**Comment by ikitommi** [comment]
Any change of doing a PR for this?

**Comment by ikitommi** [comment]
does this look correct:

```clj
(testing "pick default-charset if accepted, #79"
  (app {:headers {"content-type" "application/cheese; charset=utf-16"
                  "accept" "application/cake, text/html, application/edn"
                  "accept-charset" "x-ibm300, cheese/cake, utf-8, ibm775"}})
  (is (= [(m/map->FormatAndCharset
            {:charset "utf-16"
             :format nil
             :raw-format "application/cheese"})
          (m/map->FormatAndCharset
            {:charset "utf-8" ;; the default
             :format "application/edn"
             :raw-format "application/cake"})]
         @types)))
```

**Comment by ikitommi** [comment]
here's the new code:

```clj
(defn- -negotiate-accept [m parse s]
  (let [produces (encodes m)
        default-format (default-format m)
        accepts (parse s)]
    (or
      (and (not accepts) default-format)
      (util/some-value produces accepts)
      default-format
      (fail-on-response-format-negotiation m))))

(defn- -negotiate-accept-charset [m s]
  (let [charsets (charsets m)
        default-charset (default-charset m)
        accepts (parse/parse-accept-charset s)
        accept? (set accepts)]
    (or
      (and (not accepts) default-charset)
      (accept? default-charset)
      (util/some-value (or charsets identity) accepts)
      default-charset
      (fail-on-response-charset-negotiation m))))
```

1) if client gives nothing, use the defaults
2) prefer default on charset if ok for client
3) take first matching
4) use the default
5) fail (if default is emitted from muuntaja config)
