### ISSUE TITLE
Problem with headers

### ISSUE THREAD

**Issue by divs1210** [metosin/muuntaja#83]
Hi!
I'm using `compojure-api`, and making a GET request from my frontend code using `cljs-ajax`.
The request seems to automatically add some headers:
```
Accept: application/transit+json, application/transit+transit, application/json, text/plain, text/html, */*
```

This fails on the API and gives me the following error:
```
clojure.lang.ExceptionInfo: Malformed application/transit+json in :muuntaja/encode
```

But works when I change the header to:
```
Accept: application/json
```

**Comment by divs1210** [comment]
Actually, I want a template that just works for Compojure API + re-frame.
I've been trying to get something up and running, but its been a pain.

**Comment by ikitommi** [comment]
Hi. Most likely the response body contains values of custom types that don't have a Transit handler defined and the encoding fails.  Here's a list of types supported by Transit oob: https://github.com/cognitect/transit-clj#default-type-mapping.

The usual suspect is that you are returning a Joda DateTime, which is not supported and needs a custom transit reader & write to go over the wire. Here is a muuntaja configured to handle Joda instances over JSON & Transit:

```clj
(ns myapp.muuntaja
  (:require [cognitect.transit :as transit]
            [muuntaja.core :as m])
  (:import
    [com.fasterxml.jackson.datatype.joda JodaModule]
    [org.joda.time ReadableInstant]))

(def joda-time-writer
  (transit/write-handler
    (constantly "m")
    (fn [v] (-> ^ReadableInstant v .getMillis))
    (fn [v] (-> ^ReadableInstant v .getMillis .toString))))

(def instance
  (m/create
    (-> m/default-options
        (assoc-in
          [:formats "application/json" :opts :modules]
          [(JodaModule.)])
        (assoc-in
          [:formats "application/transit+json" :encode-opts]
          {:handlers {org.joda.time.DateTime joda-time-writer}}))))
```

**Comment by ikitommi** [comment]
If the problem still exists, Please reopen
