### ISSUE TITLE
encode-protocol doesn't work

### ISSUE THREAD

**Issue by mping** [metosin/muuntaja#84]
According to the docs, `encode-protocol` should allow for custom serialization. 
But it doesn't seem it is working; besides I couldn't find any reference to `encode-protocol` on the source code.

Example:

```
;; custom protocol to encode JSON
(defprotocol EncodeJson
  ;; the 2-arity callback
  (encode-json [this charset]))

;; mount it to a formatter
(def m
  (muuntaja/create
    (-> muuntaja/default-options
        (assoc-in
          [:formats "application/json" :encode-protocol]
          [EncodeJson encode-json]))))

;; custom record with hand-crafted JSON:
(defrecord Hello []
  EncodeJson
  (encode-json [_ _]
    (ByteArrayInputStream.
      (.getBytes "{\"hello\":\"world\"}"))))


(->> (->Hello)
     (muuntaja/encode m "application/json")
     (muuntaja/decode m "application/json"))
;;; returns an empty map instead of a {"hello":"world"} map

```

**Comment by ikitommi** [comment]
The encode-protocol seems to have been removed, as there was no real life use case for it. Sadly, the removal was not documented and the docs still claim it exists. Do you have a use case for it?

**Comment by mping** [comment]
@ikitommi not really, I figured I could use the handlers directly. The documentation did put me a bit off though.
Anyway, thanks for your work and please keep it up.
